name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        git config --global user.name "GitHub Actions Bot" 
        git config --global user.email "21f3000766@ds.study.iitm.ac.in"      
        echo "Running!"

    - name: Make Daily Commit
      run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt
          git commit -m "Daily commit - $(date)"
          git push    