name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '40 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        git config --global user.name "GitHub Actions Bot" 
        git config --global user.email "21f3000766@ds.study.iitm.ac.in"      
        echo "Running!"

    - name: Make Daily Commit
      run: |
        git commit --allow-empty -m "Daily Commit - $(date)"
        git push      