name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '9 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        git config --global user.name "S-Yousuf" 
        git config --global user.email "21f3000766@ds.study.iitm.ac.in"      
        echo "Running!"

    - name: Make Daily Commit
      run: |
          date > last-run.txt
          git add .
          git commit -m "Daily commit"
          git push origin main  